"""
File: audit.py
Path: src/api/routers/audit.py
Role: Tenant-scoped audit query and reporting endpoints.
Used By:
 - src/api/app.py
Depends On:
 - src/api/dependencies.py
 - src/api/schemas/audit_schemas.py
Notes:
 - Exposes audit records generated by the tool audit pipeline.
"""

from __future__ import annotations

from collections import Counter
from datetime import datetime, timezone
import json
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException, Query, Request

from src.api.dependencies import require_valid_identity
from src.api.schemas.audit_schemas import (
    AuditCleanupRequest,
    AuditCleanupResponse,
    AuditEventListResponse,
    AuditEventResponse,
    AuditExportFileRequest,
    AuditExportFileResponse,
    AuditExportBundleResponse,
    AuditReportResponse,
    AuditVerifyRequest,
    AuditVerifyResponse,
)
from src.compliance.evidence_bundle import (
    build_signing_keyring,
    compute_audit_chain_fingerprint,
    resolve_signing_secret,
    sign_bundle_payload,
    verify_signed_bundle_with_keyring,
)
from src.identity.contracts import IdentityContext

router = APIRouter(tags=["audit"])


def _audit_store_or_503(request: Request):
    store = getattr(request.app.state, "audit_store", None)
    if store is None:
        raise HTTPException(status_code=503, detail="Audit store is not configured.")
    return store


def _record_to_response(record) -> AuditEventResponse:
    return AuditEventResponse(
        event_id=record.event_id,
        correlation_id=record.correlation_id,
        tenant_id=record.tenant_id,
        event_type=record.event_type,
        payload=dict(record.payload),
    )


def _export_directory(request: Request) -> Path:
    root = Path(str(getattr(request.app.state.settings.limits, "audit_export_directory", ".exo_data/audit_exports")))
    root.mkdir(parents=True, exist_ok=True)
    return root.resolve()


def _build_signed_export_bundle(*, tenant_id: str, records: list, request: Request) -> dict:
    event_rows = [_record_to_response(record).model_dump() for record in records]
    chain_input_rows = [
        {
            "event_id": str(record.event_id),
            "correlation_id": str(record.correlation_id),
            "tenant_id": str(record.tenant_id),
            "event_type": str(record.event_type),
            "payload": dict(record.payload),
        }
        for record in records
    ]
    chain_valid, last_hash = compute_audit_chain_fingerprint(chain_input_rows)
    counts = Counter(str(record.event_type or "unknown") for record in records)
    payload = {
        "tenant_id": tenant_id,
        "record_count": len(records),
        "chain_valid": bool(chain_valid),
        "last_record_hash": str(last_hash),
        "event_type_counts": dict(counts),
        "records": event_rows,
        "exported_at_utc": datetime.now(timezone.utc).isoformat(),
    }
    limits = request.app.state.settings.limits
    keyring = build_signing_keyring(
        legacy_secret=str(getattr(limits, "audit_bundle_signing_secret", "exo-audit-dev-secret")),
        versioned_secrets=dict(getattr(limits, "audit_bundle_signing_secrets_by_version", {})),
    )
    signature_version, secret = resolve_signing_secret(
        active_version=str(getattr(limits, "audit_bundle_signing_active_version", "v1")),
        keyring=keyring,
    )
    payload["signature_version"] = signature_version
    payload["signature"] = sign_bundle_payload(payload, secret)
    return payload


@router.get("/{tenant_id}/admin/audit/events", response_model=AuditEventListResponse)
async def list_audit_events(
    tenant_id: str,
    request: Request,
    correlation_id: str = Query(default=""),
    limit: int = Query(default=100, ge=1, le=1000),
    _identity: IdentityContext = Depends(require_valid_identity),
) -> AuditEventListResponse:
    store = _audit_store_or_503(request)
    if correlation_id.strip():
        records = await store.query_audit_events(correlation_id=correlation_id.strip(), tenant_id=tenant_id)
    else:
        records = await store.list_audit_events(tenant_id=tenant_id, limit=limit)
    events = [_record_to_response(record) for record in records]
    return AuditEventListResponse(
        tenant_id=tenant_id,
        correlation_id=correlation_id.strip(),
        total=len(events),
        events=events,
    )


@router.get("/{tenant_id}/admin/audit/report", response_model=AuditReportResponse)
async def audit_report(
    tenant_id: str,
    request: Request,
    limit: int = Query(default=500, ge=1, le=2000),
    _identity: IdentityContext = Depends(require_valid_identity),
) -> AuditReportResponse:
    store = _audit_store_or_503(request)
    records = await store.list_audit_events(tenant_id=tenant_id, limit=limit)
    by_event_type: dict[str, int] = {}
    for record in records:
        key = str(record.event_type or "unknown")
        by_event_type[key] = by_event_type.get(key, 0) + 1
    return AuditReportResponse(
        tenant_id=tenant_id,
        total_events=len(records),
        by_event_type=by_event_type,
    )


@router.post("/{tenant_id}/admin/audit/cleanup", response_model=AuditCleanupResponse)
async def cleanup_audit_events(
    tenant_id: str,
    body: AuditCleanupRequest,
    request: Request,
    _identity: IdentityContext = Depends(require_valid_identity),
) -> AuditCleanupResponse:
    store = _audit_store_or_503(request)
    configured_cap = int(getattr(request.app.state.settings.limits, "max_audit_records_per_tenant", 10_000))
    retained_cap = int(body.max_records) if int(body.max_records) > 0 else configured_cap
    pruned = await store.cleanup_audit_events(tenant_id=tenant_id, max_records=retained_cap)
    return AuditCleanupResponse(
        tenant_id=tenant_id,
        pruned_records=int(pruned),
        retained_cap=int(retained_cap),
    )


@router.get("/{tenant_id}/admin/audit/export", response_model=AuditExportBundleResponse)
async def export_audit_bundle(
    tenant_id: str,
    request: Request,
    limit: int = Query(default=500, ge=1, le=5000),
    _identity: IdentityContext = Depends(require_valid_identity),
) -> AuditExportBundleResponse:
    store = _audit_store_or_503(request)
    configured_max = int(getattr(request.app.state.settings.limits, "max_audit_export_records", 2_000))
    bounded = min(max(int(limit), 1), max(configured_max, 1))
    records = await store.list_audit_events(tenant_id=tenant_id, limit=bounded)
    bundle = _build_signed_export_bundle(tenant_id=tenant_id, records=records, request=request)
    return AuditExportBundleResponse.model_validate(bundle)


@router.post("/{tenant_id}/admin/audit/export-file", response_model=AuditExportFileResponse)
async def export_audit_bundle_to_file(
    tenant_id: str,
    body: AuditExportFileRequest,
    request: Request,
    _identity: IdentityContext = Depends(require_valid_identity),
) -> AuditExportFileResponse:
    store = _audit_store_or_503(request)
    configured_max = int(getattr(request.app.state.settings.limits, "max_audit_export_records", 2_000))
    bounded = min(max(int(body.limit), 1), max(configured_max, 1))
    records = await store.list_audit_events(tenant_id=tenant_id, limit=bounded)
    bundle = _build_signed_export_bundle(tenant_id=tenant_id, records=records, request=request)
    sanitized_prefix = "".join(ch if ch.isalnum() or ch in {"_", "-"} else "_" for ch in str(body.filename_prefix))
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")
    filename = f"{sanitized_prefix}_{tenant_id}_{timestamp}.json"
    export_dir = _export_directory(request)
    file_path = (export_dir / filename).resolve()
    if export_dir not in file_path.parents:
        raise HTTPException(status_code=400, detail="Invalid export file path.")
    file_path.write_text(json.dumps(bundle, indent=2, sort_keys=True), encoding="utf-8")
    return AuditExportFileResponse(
        tenant_id=tenant_id,
        file_path=str(file_path),
        record_count=int(bundle["record_count"]),
        signature_version=str(bundle.get("signature_version", "v1")),
        signature=str(bundle["signature"]),
        chain_valid=bool(bundle["chain_valid"]),
        last_record_hash=str(bundle["last_record_hash"]),
    )


@router.post("/{tenant_id}/admin/audit/verify", response_model=AuditVerifyResponse)
async def verify_audit_bundle(
    tenant_id: str,
    body: AuditVerifyRequest,
    request: Request,
    _identity: IdentityContext = Depends(require_valid_identity),
) -> AuditVerifyResponse:
    bundle_data: dict
    if str(body.file_path).strip():
        export_dir = _export_directory(request)
        candidate = Path(str(body.file_path)).resolve()
        if export_dir != candidate and export_dir not in candidate.parents:
            raise HTTPException(status_code=400, detail="file_path must be inside audit export directory.")
        if not candidate.exists():
            raise HTTPException(status_code=404, detail="Audit export file not found.")
        bundle_data = json.loads(candidate.read_text(encoding="utf-8"))
    elif body.bundle:
        bundle_data = dict(body.bundle)
    else:
        raise HTTPException(status_code=422, detail="Either file_path or bundle payload must be provided.")

    if str(bundle_data.get("tenant_id", "")) != tenant_id:
        return AuditVerifyResponse(
            tenant_id=tenant_id,
            signature_version=str(bundle_data.get("signature_version", "")),
            verified_with_version="",
            signature_valid=False,
            chain_valid=False,
            verified=False,
            reason="TENANT_MISMATCH",
        )
    signature = str(bundle_data.get("signature", "")).strip()
    declared_signature_version = str(bundle_data.get("signature_version", "")).strip()
    payload_without_signature = dict(bundle_data)
    payload_without_signature.pop("signature", None)
    limits = request.app.state.settings.limits
    keyring = build_signing_keyring(
        legacy_secret=str(getattr(limits, "audit_bundle_signing_secret", "exo-audit-dev-secret")),
        versioned_secrets=dict(getattr(limits, "audit_bundle_signing_secrets_by_version", {})),
    )
    signature_valid, verified_with_version = verify_signed_bundle_with_keyring(
        payload=payload_without_signature,
        signature=signature,
        declared_version=declared_signature_version,
        keyring=keyring,
    )

    chain_rows = []
    for row in list(bundle_data.get("records", [])):
        chain_rows.append(
            {
                "event_id": str(row.get("event_id", "")),
                "correlation_id": str(row.get("correlation_id", "")),
                "tenant_id": str(row.get("tenant_id", "")),
                "event_type": str(row.get("event_type", "")),
                "payload": dict(row.get("payload", {})),
            }
        )
    computed_chain_valid, computed_last_hash = compute_audit_chain_fingerprint(chain_rows)
    declared_chain_valid = bool(bundle_data.get("chain_valid", False))
    declared_last_hash = str(bundle_data.get("last_record_hash", ""))
    chain_valid = bool(computed_chain_valid and declared_chain_valid and computed_last_hash == declared_last_hash)
    verified = bool(signature_valid and chain_valid)
    return AuditVerifyResponse(
        tenant_id=tenant_id,
        signature_version=declared_signature_version,
        verified_with_version=verified_with_version,
        signature_valid=signature_valid,
        chain_valid=chain_valid,
        verified=verified,
        reason="" if verified else "AUDIT_BUNDLE_VERIFICATION_FAILED",
    )
